name: Daily Automation

on:
  schedule:
    - cron: "30 18 * * *"  # every day at 00:00 IST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run_metrics:
    uses: ./.github/workflows/metrics.yml
    secrets: inherit
