name: ðŸ’¡ Coding Habits and Activity

on:
  workflow_call:
    secrets:
      METRICS_TOKEN:
        required: true

permissions:
  contents: write

jobs:
  generate-habits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Coding Habits and Activity Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: nihaltp

          filename: metrics/habits.svg
          base: ""
          output_action: commit
          output_action_branch: output
          output_action_commit_message: "chore: update coding habits metrics"

          plugin_habits: yes
          plugin_habits_from: 300
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph
          plugin_habits_trim: yes
          plugin_habits_languages_limit: 6
          plugin_habits_languages_threshold: 1%
          config_timezone: Asia/Kolkata
